version: '3.8'

services:
  master_db:
    container_name: master_db
    image: 192.168.192.203:5000/db_image
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication repl_user ${DB_REPL_HOST}/24 scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - pg_logs:/var/log/postgresql
      - db_data:/var/lib/postgresql/data
    command: |
      postgres 
        -c archive_mode=on 
        -c archive_command='cp %p /oracle/pg_data/archive/%f' 
        -c max_wal_senders=10 
        -c wal_level='replica' 
        -c log_replication_commands='on' 
        -c wal_log_hints='on'
        -c logging_collector='on' 
        -c log_directory='/var/log/postgresql' 
        -c log_filename='postgresql-15-main.log'
    networks:
      project_network:
        ipv4_address: 172.16.111.10
    ports:
      - "5432:5432"
    restart: always

  slave_db:
    container_name: slave_db
    image: 192.168.192.203:5000/db_repl_image
    environment:
      PGUSER: ${DB_REPL_USER}
      PGPASSWORD: ${DB_REPL_PASSWORD}
    command: |
      bash -c "
      rm -rf /var/lib/postgresql/data/* &&
      pg_basebackup -R -h master_db -D /var/lib/postgresql/data
      sleep 5s
      chmod 0700 /var/lib/postgresql/data
      postgres
      "
    networks:
      project_network:
        ipv4_address: 172.16.111.11
    volumes:
      - repl_db_data:/var/lib/postgresql/data
    restart: always
    depends_on:
      - master_db

  bot:
    container_name: bot
    image: 192.168.192.203:5000/bot_image
    environment:
      TOKEN: ${TOKEN}
      RM_HOST: ${RM_HOST}
      RM_PORT: ${RM_PORT}
      RM_USER: ${RM_USER}
      RM_PASSWORD: ${RM_PASSWORD}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
    networks:
      project_network:
        ipv4_address: 172.16.111.12
    volumes:
      - pg_logs:/var/log/postgresql:ro
    depends_on:
      - master_db

networks:
  project_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.111.0/24


volumes:
  db_data:
  repl_db_data:
  pg_logs:
